spring:
  application:
    name: ym-blog
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ym-blog
    username: root
    password: yunmao
  session:
    store-type: redis
    timeout: 3600 # session 超时时间（秒）
  redis:
    # 连接地址
    host: "localhost"
    # 端口
    port: 6379
    # 数据库
    database: 0
    # 用户名，如果有
    # username:
    # 密码，如果有
    # password:
    # 连接超时
    connect-timeout: 5s
    # 读超时
    timeout: 5s

    # Lettuce 客户端的配置
    lettuce:
      # 连接池配置
      pool:
        # 最小空闲连接
        min-idle: 0
        # 最大空闲连接
        max-idle: 8
        # 最大活跃连接
        max-active: 8
        # 从连接池获取连接 最大超时时间，小于等于0则表示不会超时
        max-wait: -1ms
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    # 仅在开发环境开启日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: "云猫博客接口文档"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.ym.blogBackEnd.controller

ym:
  # 用户配置
  user:
    register-email-code-expire-time: 3 # 邮箱验证码过期时间（分钟）
    register-email-code-length: 6 # 邮箱验证码长度
    password-salt: YunMao # 密码加盐
    password-min-length: 9 # 密码最短长度
    account-min-length: 8 # 账号最短长度
    default-password: 123456 # 默认密码






